name: flowcli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  process_run: ^0.12.2+2
  date_format: ^2.0.4
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
